### ISSUE TITLE
Display Data

### ISSUE THREAD

**Issue by Kangaroo6942** [hpi-swa-teaching/MensaWidget#10]
### User Story
**As a** user **I want** to view the outlet data, **to** get informed about meal options.

### Development Goals

- [ ] Implementation
- [ ] Testing
- [ ] Documentation

### Sucess Criteria

- [x] widget sized
- [x] compact not too bloated
- [x] clean with easy overview
- [ ] ~clear error messages~ -> not in the scope of this ticket
- [x] categorize by outlets
- [x] handle weekend

**Comment by OscarUlb** [comment]
With the latest commit the scaling got better but i could not figure out how to pass the Framesize to the CanteenMorph and MealMorph. Mabey we can talk about that in person.

**Comment by lchristus** [comment]
Feedback from the customer includes that the folloing should be improved:

- [ ] close everything when minimizing the window
- [ ] possibly have a nice background? appropiate color of course...
- [ ] display currency with the price
- [ ] even spacing in top and bottom
- [ ] have texts read only
