### ISSUE TITLE
Itembar Button

### ISSUE THREAD

**Issue by tommccaughey** [hpi-swa-teaching/MensaWidget#2]
### User Story
**As a** user **I want to** access the Mensa Widget via the toolbar, by clicking on an icon, **to** quickly open the widget.

### Development Goals

- [ ] Implementation
- [ ] Testing
- [ ] Documentation

**Comment by lchristus** [comment]
we still need to figure out how to insert the functionality into the sqeak default code @Kangaroo6942 we maybe should ask the ta's for that one.

**Comment by Kangaroo6942** [comment]
I could go to the SWA chair tomorrow, that fine?

**Comment by lchristus** [comment]
This should also include the functionality of https://github.com/hpi-swa-teaching/MensaWidget/issues/44 and have the item togglable with a preference tab.
