### ISSUE TITLE
Layout

### ISSUE THREAD

**Issue by tommccaughey** [hpi-swa-teaching/MensaWidget#3]
### User Story
**As a** user **I want** a small, simple, moveable Window **to** view my daily meal options. 

### Development Goals

- [ ] Implementation
- [ ] Testing
- [ ] Documentation

**Comment by tommccaughey** [comment]
- Squeak Window

**Comment by lchristus** [comment]
@OscarUlb @Kangaroo6942 I just implemented some simple test for the window. Maybe give me some feedback if this is about how you envisioned the test suite or not?

**Comment by Kangaroo6942** [comment]
Looks good to me, but do we really want to test that the window is not called "untitled window" or rather the name that the window should have

**Comment by lchristus** [comment]
> Looks good to me, but do we really want to test that the window is not called "untitled window" or rather the name that the window should have

yes I would agree eventually but since we haven't decided on a name I implemented it this way for now. But I do agree and I also would suggest we just keep the name MensaWidget as header but that is a topic we need to discuss internaly.
