### ISSUE TITLE
Text Scaling

### ISSUE THREAD

**Issue by lchristus** [hpi-swa-teaching/MensaWidget#46]
The text size depends on the sclaing factor, while the mensa widget does not leading to the text being nicely alligned when there is a high scaling factor. We need the max line number to be dependent on the text scaling factor.

**Comment by OscarUlb** [comment]
I have committed some initial changes for testing purposes. Additionally, I have updated the widget to display the meals for 2024-06-07. Since “it works on my machine,” I would appreciate any feedback to ensure the scaling appears correctly on all systems.
