### ISSUE TITLE
API Call

### ISSUE THREAD

**Issue by Kangaroo6942** [hpi-swa-teaching/MensaWidget#8]
### User Story
**As a** developer **I want** a function that returns the data from a specific outlet, **to** have a uniform access point to the outlet data. 

### Development Goals

- [ ] Implementation
- [ ] Testing
- [ ] Documentation

**Comment by OscarUlb** [comment]
@Kangaroo6942 @lchristus I have just pushed an initial solution for the issue to the branch. Could you please take a look and provide feedback on whether any functionalities are still missing?

**Comment by Kangaroo6942** [comment]
@OscarUlb Looks good, i just would like to see a space between the "^" and the return value in the class methods, or is there some idiom I am missing? (But please don't push yet)

**Comment by lchristus** [comment]
I like it as well functionality works great, I just have a style improvement because you can use cascades for the two replace statements. And just a idea I want to pitch is that we could have a guarding clause the makes sure both inputs since we might walk into trouble if we allow that, but just a idea.

**Comment by Kangaroo6942** [comment]
Another thing I already talked to @OscarUlb about is that the function should handle the case of not getting a server response or getting an error response, e.g. when the user does not have an internet connection

**Comment by lchristus** [comment]
> e user does not have an internet connection

Yes makes sense we should look into throwing errors or something along those lines, but you also agree we should handle wrong input types?

**Comment by Kangaroo6942** [comment]
i am currently in two minds about this... On the one hand I'd like to say the code is stable and we catch any wrong input with some error code which the caller can handle, on the other hand if we do it once we kind of have to do it for everything else which makes the codebase a lot bigger since we have to check every function parameter for correctness
I personally would like to assume that the functions are used as they are intended, since especially for the issues we are currently working on, no user interaction is required

**Comment by Kangaroo6942** [comment]
I just wish smalltalk was typed statically...
